# generated by datamodel-codegen:
#   filename:  openapi.yml
#   timestamp: 2024-12-05T12:59:22+00:00

from __future__ import annotations
from pydantic import EmailStr, AnyHttpUrl
from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, SecretStr



class LoginUser(BaseModel):
    email: str
    password: SecretStr


class RegisterUser(BaseModel):
    username: str
    email: str
    password: str


class UserInResponse(BaseModel):
    email: EmailStr
    token: str
    username: str
    bio: str | None = ""
    image: str | None = None

class UserInDB(BaseModel):
    id: int #変えるかも
    email: EmailStr
    username: str
    password: str
    bio: Optional[str] = ""
    image: Optional[AnyHttpUrl] = None #型変えるかも


class UpdateUser(BaseModel):
    email: Optional[str] = None
    password: Optional[str] = None
    username: Optional[str] = None
    bio: Optional[str] = None
    image: Optional[str] = None


class Profile(BaseModel):
    username: str
    bio: str
    image: str
    following: bool




class Errors(BaseModel):
    body: List[str]


class GenericErrorModel(BaseModel):
    errors: Errors

class Token(BaseModel):
    access_token: str
    token_type: str = "bearer"


class TokenPayload(BaseModel):
    sub: str | None = None